pub const SPECIALTIES_STRINGS: [&str; 137] = [
"Anestezjologia i intensywna terapia",
"Angiologia",
"Audiologia i foniatria",
"Balneologia i medycyna fizykalna",
"Chirurgia dziecięca",
"Chirurgia klatki piersiowej",
"Chirurgia naczyniowa",
"Chirurgia ogólna",
"Chirurgia onkologiczna",
"Chirurgia plastyczna",
"Chirurgia stomatologiczna",
"Chirurgia szczękowo-twarzowa",
"Chirurgia torakochirurgia",
"Chirurgia transplantacyjna",
"Chirurgia urazowa",
"Chirurgia wady wrodzone",
"Chirurgia żołądka",
"Choroby płuc",
"Choroby wewnętrzne",
"Choroby zakaźne",
"Dermatologia i wenerologia",
"Diabetologia",
"Diagnostyka laboratoryjna",
"Diagnostyka obrazowa",
"Diagnostyka ultrasonograficzna",
"Endokrynologia",
"Epidemiologia",
"Farmakologia kliniczna",
"Fizjoterapia",
"Gastroenterologia",
"Genetyka kliniczna",
"Geriatria",
"Ginekologia onkologiczna",
"Hematologia",
"Higiena i epidemiologia",
"Immunologia kliniczna",
"Kardiochirurgia",
"Kardiologia dziecięca",
"Kardiologia interwencyjna",
"Kardiologia inwazyjna",
"Kardiologia",
"Medycyna estetyczna",
"Medycyna lotnicza",
"Medycyna nuklearna",
"Medycyna paliatywna",
"Medycyna pracy",
"Medycyna ratunkowa",
"Medycyna rodzinna",
"Medycyna sądowa",
"Medycyna sportowa",
"Medycyna transportu",
"Medycyna tropikalna",
"Medycyna weterynaryjna",
"Medycyna wojskowa",
"Medycyna zapobiegawcza",
"Mikrobiologia lekarska",
"Nefrologia dziecięca",
"Nefrologia",
"Neonatologia",
"Neurochirurgia dziecięca",
"Neurochirurgia",
"Neurologia dziecięca",
"Neurologia kliniczna",
"Neurologia onkologiczna",
"Neurologia wieku rozwojowego",
"Neurologia wieku rozwojowego", 
"Neurologia z elementami neurochirurgii",
"Neurologia z elementami psychiatrii",
"Neurologia",
"Okulistyka",
"Onkologia i hematologia dziecięca",
"Onkologia kliniczna",
"Onkologia radioterapia",
"Onkologia",
"Ortodoncja",
"Ortopedia dziecięca",
"Ortopedia i traumatologia narządu ruchu",
"Ortopedia onkologiczna",
"Ortopedia urazowa",
"Ortopedia z elementami chirurgii urazowej",
"Ortopedia",
"Otolaryngologia dziecięca",
"Otolaryngologia onkologiczna",
"Otolaryngologia z elementami audiologii",
"Otolaryngologia z elementami chirurgii plastycznej",
"Otolaryngologia z elementami chirurgii szczękowo-twarzowej",
"Otolaryngologia z elementami chirurgii urazowej",
"Otolaryngologia z elementami foniatrii",
"Otolaryngologia z elementami laryngologii dziecięcej",
"Otolaryngologia z elementami otologii",
"Otolaryngologia z elementami rekonstrukcji przewodów słuchowych",
"Otolaryngologia",
"Otorynolaryngologia",
"Patomorfologia",
"Pediatria onkologiczna",
"Pediatria z elementami alergologii",
"Pediatria z elementami endokrynologii",
"Pediatria z elementami gastroenterologii",
"Pediatria z elementami hematologii",
"Pediatria z elementami kardiologii",
"Pediatria z elementami nefrologii",
"Pediatria z elementami neurologii",
"Pediatria z elementami onkologii",
"Pediatria z elementami pulmonologii",
"Pediatria z elementami reumatologii",
"Pediatria z elementami toksykologii",
"Pediatria",
"Położnictwo i ginekologia",
"Psychiatria dzieci i młodzieży",
"Psychiatria geriatryczna",
"Psychiatria sądowa",
"Psychiatria z elementami seksuologii",
"Psychiatria z elementami terapii uzależnień",
"Psychiatria",
"Radiologia i diagnostyka obrazowa",
"Radioterapia onkologiczna",
"Rehabilitacja medyczna",
"Reumatologia",
"Seksuologia",
"Stomatologia dziecięca",
"Stomatologia zachowawcza",
"Stomatologia",
"Toksykologia kliniczna",
"Urologia dziecięca",
"Urologia onkologiczna",
"Urologia z elementami andrologii",
"Urologia z elementami chirurgii onkologicznej",
"Urologia z elementami endokrynologii",
"Urologia z elementami ginekologii",
"Urologia z elementami nefrologii",
"Urologia z elementami onkologii",
"Urologia z elementami radiologii",
"Urologia z elementami seksuologii",
"Urologia z elementami uroginekologii",
"Urologia z elementami urologii dziecięcej",
"Urologia",
"Zdrowie publiczne"
];
